# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_used',
        ),
    ]
