# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180325_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='questions', to='categories.Category'),
        ),
    ]
