# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20180326_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_body',
            field=models.CharField(max_length=1024, null=True, verbose_name='\u0422\u0435\u043b\u043e \u0432\u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
    ]
